[package]
name = "woxar"
version = "0.1.0"
authors = ["Jonathan Phénix <greaterd@gmail.com>"]
edition = "2018"

[dependencies]
bit-vec = "0.6"
clap = "2"
smallvec = "1"
byteorder = "1"
thiserror = "1"
anyhow = "1"
